version: "3"

services:

  contextmap:
    container_name: community-edition
    image: contextmap/community-edition:latest
    ports:
      - 8080:80
      - 8000:8000
    environment:
      - "BACKEND_URL=http://localhost:8000"
    volumes:
      - ./tmp:/data/db

  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker/rabbitmq/rabbitmq.security:/etc/rabbitmq/rabbitmq.security:ro

  postgres-container:
    image: postgres:13.1-alpine
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shopping-cart

#  jenkins:
#    image: jenkins/jenkins:latest
#    privileged: true
#    user: root
#    extra_hosts:
#      - "localhost:192.168.88.120"
#    ports:
#      - 8081:8081
#      - 50000:50000
#    container_name: jenkins-ctxmp-community
#    volumes:
#      - "/Users/psavat/dev/villaratio/repos/github/example-docker-community-edition:/my-project:ro"
#    environment:
#      - "JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
#      - "JENKINS_OPTS=--httpPort=8081"
