pipeline {
    agent any
    stages {
        stage('Prepare') {
            steps {
                sh './mvnw --version'
                sh 'java --version'
            }
        }
        stage('Compile') {
            steps {
                sh './mvnw clean compile'
            }
        }
        stage('Unit Test') {
            steps {
                sh './mvnw verify'
            }
        }
    }
}
