pipeline {
    agent any
    stages {
        stage('Prepare') {
            steps {
                sh './mvnw --version'
                sh 'java --version'
            }
        }
        stage('Compile') {
            steps {
                sh './mvnw clean compile'
            }
        }
        stage('Unit Test') {
            steps {
                sh './mvnw verify'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                echo 'Killing the following processes'
                sh "ps -ef | grep spring-boot | grep -v grep |  awk '{print $2}'"
                sh "ps -ef | grep spring-boot | grep -v grep |  awk '{print $2}' | xargs -r kill"
                echo 'Starting the service'
                sh 'mvn spring-boot:run &'
                echo 'Deployed'
            }
        }
    }
}
